### ISSUE TITLE
블로그/dev/python 항목의 작성과 수정에 대해 궁금합니다

### ISSUE THREAD

**Issue by HaJunMyoung** [zerosheepmoo/hayangbum-techb#6]
블로그에 본인이 학습한 내용을 정리하기로 했는데,
william son과 제가 배운 내용을 각각 적으면 내용들이 중복되지 않을까요?

먼저 쓰는 사람이 임자고 후발주자가 수정 및 추가하는 건가요?ㅋㅋ

**Comment by zerosheepmoo** [comment]
각자 부분을 정해놓든 번갈아가면서 쓰든 하기를 바랍니다.
본래 어제 회의 시간에 정했어야 했는데 못했네요.
제 생각에는 양이 많다면 각자 부분을 정하거나 이틀에 한번씩 하기로, 양이 적다면 python tutorial을 공부한 것을 덧붙여 적어놓으면 좋겠네요!

**Comment by HaJunMyoung** [comment]
음. 이해했습니다
