### ISSUE TITLE
python 항목-python-feature 오류

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/hayangbum-techb#7]
@HaJunMyoung 
인터프리터의 뜻이 조금 엇나갔습니다.
재조사 후 작성해주세요.
논문 인용같은 것도 괜찮습니다.

[인터프리터와 컴파일러의 차이](https://techdifferences.com/difference-between-compiler-and-interpreter.html)

**Comment by HaJunMyoung** [comment]
수정 사항 커밋했습니다. 잠시 후 다른 변경사항들과 함께 푸쉬할 예정이니 그 때 재차 확인 부탁합니다.
