### ISSUE TITLE
yarn dev 에 관한 오류 원인 추정

### ISSUE THREAD

**Issue by HaJunMyoung** [zerosheepmoo/hayangbum-techb#8]
## 추정
기존 레포지토리에 있는 yarn과 새로 설치하는 yarn or vuepress 사이의 충돌이 있는 것이 아닐까 추측해봅니다.

## 근거(성공케이스)
```
$ yarn init
$ yarn install
$ yarn add vuepress -D
```
을 통해 localhost:8080 에서 테스트하기 위한 준비를 하고 (새 폴더에서)
(`yarn vuepress dev .`을 통해 README.md 파일이 잘 표시되는지 확인하고),
techb repository에서 src 폴더를 가져와 `yarn vuepress dev src`를 수행하면, **정상적으로 표현됩니다**

## 근거(실패케이스)
먼저, clone 된 techb repository를 복사하고, package.json 파일은 생성되어 있기에 `init`은 생략합니다.
```
$ yarn install
$ yarn add vuepress -D
```
하여, `dev`하면, 일전과 같은 오류를 만날 수 있습니다.

하지만, **성공케이스**와 비교해 보았을 때, git 관련 폴더 및 파일을 제외하고는 특별한 차이점이 없습니다. node_modules 폴더 역시 구성이 완전히 동일한 것으로 보입니다.

따라서, **기존에 설치되어 있던 내용들이 새로 설치되는 것들과 일종의 충돌**을 일으키는 것으로 보입니다.

## 근거(더 많은 실패케이스)
다음과 같은 시도들도 해보았습니다만, 모두 실패했습니다.

1. 폴더의 이름을 유동적으로 조정해보기
    >공백, 한글 등을 넣어보기도, 빼보기도 했습니다.
1. `yarn init`을 생략하지 않고 복사된 레포지토리에서 시도해보기
    >`init`부터 `vuepress`까지 모두 해보았습니다.
1. `yarn dev`를 바로 실행해보기
    >vuepress가 없다는 에러메세지를 줍니다
1. `yarn install` 없이 `add vuepress`하여 빌드해보기
    >빌드는 되지만 페이지 표현은 되지 않습니다.

## 궁금한 점
다른 사용자분들도 이 과정을 따라 `dev`를 시도해보고, 어떤지 피드백을 주시기 바랍니다.

1. techb repository를 copy&paste
1. paste된 repository 폴더에서 `init` (optional) -> `install` -> `add vuepress -D` -> `dev`

**Comment by zerosheepmoo** [comment]
# 의견

매우 흥미로운 문제제기 입니다. 그러나 몇 가지 개념에 오류가 있습니다.

> yarn 은 package manager 입니다.

yarn은 특정 디렉토리에 패키지 형태로 되어있는 게 아닌,
컴퓨터 내부 시스템 영역에 등록되어 (즉, 인스톨되어) 있습니다.
또 CLI 가 가능한 것은 `yarn`이라는 명령어를 시스템 글로벌 영역에 등록한 것입니다.

> git clone 시 클론된 것은 `package.json` 파일과 소스파일이 전부입니다.

`node_modules` 내에 있는 패키지들은 pacakge.json 파일들에 등록되어 있는 dependencies 항목들과 devdependencies 항목을 읽어 기본 모듈들과 함께 설치합니다. 그 후에 yarn 내부적으로 의존성관리나 패키지관리를 생성된 `yarn.lock`파일에서 하게됩니다.

# 결론

[`yarn.lock`을 프로젝트에 포함시켜야 하는이유](https://www.daleseo.com/js-package-locks/)를 살펴보면 프로젝트 매니저가 패키지 버전을 고정시키기 위해서는 깃허브에 같이 업로드 해주어야합니다. 그러니 제가 고정된 버전으로 설치가 되어있는 락 파일을 깃에 푸쉬한 것이지요.

현재 발생하는 상황을 봤을 때 락 파일에 옳지 못한 구성이 있어 패키지 관리에 문제가 생긴 듯합니다.
이는 아마 제 로컬영역에서 패키지 인스톨을 성공적으로 마친 후 lock파일이 손상된 상태로 깃허브에 푸쉬되었거나, 
윈도우랑 맥에서 지원되는 버전이 달라 픽스되어있는 버전이 윈도우즈에서는 작동하지 않는 것일 수도 있습니다.

문제 상황이 많이 좁혀지게 되어 기쁩니다 😄

**Comment by HaJunMyoung** [comment]
음, 여러가지 가능성이 있군요. 모쪼록 무엇이 원인인지 빨리 밝혀졌으면 하네요ㅎㅎ
