### ISSUE TITLE
마크다운: 디테일 문법이 적용되지 않습니다.

### ISSUE THREAD

**Issue by hajun-myoung** [zerosheepmoo/hayangbum-techb#9]
# 문제상황
```
::: details
:::
```
가 적용되지 않습니다.

## 기타
```
::: tip
:::

::: warning
:::

::: danger
:::
```
모두 잘 작동합니다.

**Comment by zerosheepmoo** [comment]
우선 본래는 그럴일이 없어야함을 밝힙니다. vuepress 패키지를 프로젝트에서 명시해준 버전을 사용한다면, 저와 하준 씨가 동일하게 작동하여야합니다.

다음의 이유로 작동이 안될 수 있습니다.

하준 씨가 새 버전의 패키지를 설치하거나, 설정한 경우.
이 경우 패키지 정보확인이나 `yarn lock`의 소스를 대조해볼 필요가 있습니다.
확인해주시고 다시 이슈답변 주십시오.

- ::: 하고 띄어쓰기 안해서 작동 안될 수도 있습니다.
